### ISSUE TITLE
Job parameters default via Symfony config

### ISSUE THREAD

**Issue by yann-eugone** [yokai-php/batch-src#122]
### Description

Following #93, it could be a good idea to have a way to provide parameters defaults via Symfony configuration.

### Example

```
yokai_batch:
  default_parameters:
    global:
      foo: bar
    jobs:
      job.name:
        foo: baz    
```
